CREATE TABLE tb_point
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    timestamp  TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_tb_point PRIMARY KEY (id)
);

CREATE TABLE tb_users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(255),
    email           VARCHAR(255),
    cpf             VARCHAR(255),
    password        VARCHAR(255),
    roles            VARCHAR(255),
    work_journey_id BIGINT,
    CONSTRAINT pk_tb_users PRIMARY KEY (id)
);

CREATE TABLE tb_work_journey
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description            VARCHAR(255),
    status                 VARCHAR(255),
    daily_workload_minutes INTEGER,
    minimum_break_minutes  INTEGER,
    CONSTRAINT pk_tb_work_journey PRIMARY KEY (id)
);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_cpf UNIQUE (cpf);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_email UNIQUE (email);

ALTER TABLE tb_point
    ADD CONSTRAINT FK_TB_POINT_ON_USER FOREIGN KEY (user_id) REFERENCES tb_users (id);

ALTER TABLE tb_users
    ADD CONSTRAINT FK_TB_USERS_ON_WORK_JOURNEY FOREIGN KEY (work_journey_id) REFERENCES tb_work_journey (id);